<?php
$orderId = Mage::getSingleton("checkout/session")->getLastOrderId();
$order = Mage::getModel("sales/order")->load($orderId);
$payment = $order->getPayment();
if($payment->getMethod() == 'yapay_creditcardpayment'){
    $creditcardBlock = $this->getChild('card');
    if ($creditcardBlock) {
        $creditcardBlock->setData('order', $order);
        $creditcardBlock->setData('payment', $payment);
        echo $this->getChildHtml('card');
    }
}elseif($payment->getMethod() == 'yapay_backslippayment'){
    echo $this->getChildHtml('bankslip'); 
}elseif($payment->getMethod() == 'yapay_pixpayment'){
    echo $this->getChildHtml('pix');
}
?>
