<?php
$helper = Mage::helper("mageshop_yapay/data");
$payment = $this->getPayment();
$order = $this->getOrder();
$customerId = $order->getCustomerId();
$customer = Mage::getModel('customer/customer')->load($customerId);
$customerName = $customer->getName();
$customerEmail = $customer->getEmail();
?>

<div class="container_yapay_payment">
    <div class="vindi"></div>
    <div class="yapay_data_payment">
        <div class="yapay_payment_icon <?php echo $helper->__( $this->_status( $payment->getAdditionalInformation("status_id") )); ?>"></div>
        <h2 class="yapay_payment_status"> <?php echo $helper->__( $payment->getAdditionalInformation("status_name") ); ?></h2>
        <h4 class="yapay_payment_status">
            <?php echo $helper->__( $this->_message( $payment->getAdditionalInformation("status_id") ), $customerName , $customerEmail ); ?>
        </h4>
        <div class="yapay_table_list_data_payment">
            <ul>
                <li>
                    <span><?php echo $helper->__("Número da transação no Vindi Intermediador:"); ?></span>
                    <b><?php echo $helper->__('#%s', $payment->getAdditionalInformation("transaction_id"));?></b>
                </li>
                <li>
                    <span><?php echo $helper->__('Meio de Pagamento:');?></span><b><?php echo $helper->__( $payment->getMethodInstance()->getTitle() );?></b>
                </li>
            </ul>
        </div>
    </div>
</div>