<?php
$helper = Mage::helper("mageshop_yapay/data");
$payment = $this->getPayment();
$order = $this->getOrder();
$customerId = $order->getCustomerId();
$customer = Mage::getModel('customer/customer')->load($customerId);
$customerName = $customer->getName();
$customerEmail = $customer->getEmail();
$transaction =  $payment->getAdditionalInformation("transaction");
$paymentYapay = $payment->getAdditionalInformation("payment");
?>

<div class="container_yapay_payment">
    <div class="vindi"></div>
    <div class="yapay_data_payment">
        <div class="yapay_payment_icon <?php echo $helper->__( $this->_status( $payment->getAdditionalInformation("status_id") )); ?>"></div>
        <h2 class="yapay_payment_status"> <?php echo $helper->__( $payment->getAdditionalInformation("status_name") ); ?></h2>
        <h4 class="yapay_payment_status">
            <?php echo $helper->__( $this->_message( $payment->getAdditionalInformation("status_id") ), $customerName , $customerEmail ); ?>
        </h4>
        <div class="yapay_table_list_data_payment">
            <ul>
                <li>
                    <object data="<?php echo $paymentYapay['qrcode_path']?>" width="250" height="250" style="padding: 30px 0;"></object>
                </li>
                <li>
                    <div class="copyCode">
                        <input type="text" value="<?php echo $paymentYapay['qrcode_original_path'];?>" id="pixTextYapay">
                        <button type="button" class="fieldcopycode" onclick="copiarTextoYapay(this)" data-code="<?php echo $paymentYapay['qrcode_original_path'];?>">Copiar</button>
                        <p class="info-expire">
                            <?php echo $helper->__("O QR Code expira em:"); ?>
                            <?php echo date('d/m/Y H:i:s', strtotime($transaction['max_days_to_keep_waiting_payment'])); ?>.
                            <br/>
                            <?php echo $helper->__("Você também pode fazer o pagamento na seção Minha Conta > Pedidos"); ?>
                        </p>
                    </div>
                </li>
                <li>
                    <span><?php echo $helper->__("Número da transação no Vindi Intermediador:"); ?></span>
                    <b><?php echo $helper->__('#%s', $payment->getAdditionalInformation("transaction_id"));?></b>
                </li>
                <li>
                    <span><?php echo $helper->__('Meio de Pagamento:');?></span><b><?php echo $helper->__( $payment->getMethodInstance()->getTitle() );?></b>
                </li>
            </ul>
        </div>
    </div>
</div>


<script type="text/javascript">
function copiarTextoYapay(button) {
  var codigoPix = button.getAttribute("data-code"); // Obtém o valor do atributo data-code
  var elementoTemporario = document.createElement("input"); // Cria um elemento temporário (input)
  document.body.appendChild(elementoTemporario); // Adiciona o elemento temporário ao corpo da página
  elementoTemporario.value = codigoPix; // Define o valor do elemento temporário como o código PIX
  elementoTemporario.select(); // Seleciona o texto dentro do elemento temporário
  elementoTemporario.setSelectionRange(0, 99999); // Para dispositivos móveis
  document.execCommand("copy"); // Copia o texto selecionado para a área de transferência
  document.body.removeChild(elementoTemporario); // Remove o elemento temporário
    setTimeout(function(){
        button.style.backgroundColor = "#00a3ff";
        button.style.borderColor = "#2591cf";
    }, 6000)
    button.style.backgroundColor = "#117e31";
    button.style.borderColor = "#096223";
}
</script>