<?php 
$_code = $this->getMethodCode(); 
$helper = $this->getHelper();
$_helper_interest = Mage::helper("mageshop_yapay/interest");
$intallmentsActive = $_helper_interest->getInterestActive();
$totals = Mage::getSingleton('checkout/session')->getQuote()->getBaseGrandTotal();
$intallments = $this->getInstallments($totals);
$splitJs = $intallmentsActive == false ? 'getSplitValues()' : '';
?>
<fieldset class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
      
        <ul data-yapay="payment-form">
            <input type="hidden" id="url_controller" value="<?php echo Mage::getUrl('yapay'); ?>">
            <input type="hidden" id="<?php echo $_code ?>_cc_payment_code" name="payment[<?php echo $_code ?>_cc_payment_code]" class="required-entry" value=""/>
            <li>             
                <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $helper->__('Credit Card Number') ?> </label>      
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_cc_number" 
                    name="payment[<?php echo $_code ?>_cc_number]" 
                    title="<?php echo $helper->__('Credit Card Number') ?>" 
                    class="required-entry input-text validate-cc-number" 
                    placeholder="&bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull;" 
                    autocomplete="off"/>
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $helper->__('Name on Card') ?> </label>
                <div class="input-box">
                    <input type="text" title="<?php echo $helper->__('Name on Card') ?>"
                    name="payment[<?php echo $_code ?>_cc_name]"
                    class="required-entry input-text validate-name" id="<?php echo $_code ?>_cc_owner" 
                    name="payment[<?php echo $_code ?>_cc_name]" 
                    placeholder="" onkeypress="return apenasLetras(event,this);"/>
                </div>
            </li>          

            <li class="fields">
                <div class="card-data">
                    <div class="field card-expires_at">
                        <label for="expires_at" class="required"><em>*</em><?php echo $helper->__("Mês Vencimento") ?></label>
                        <div class="input-box">
                            <select name="payment[<?php echo $_code ?>_expiration_month]" class="input-text required-entry validate-expirymonth" >
                                <option selected disabled><?php echo $helper->__("Month") ?></option>
                                <option value="01">1 - <?php echo $helper->__("Janeiro") ?></option>
                                <option value="02">2 - <?php echo $helper->__("Fevereiro") ?></option>
                                <option value="03">3 - <?php echo $helper->__("Março") ?></option>
                                <option value="04">4 - <?php echo $helper->__("Abril") ?></option>
                                <option value="05">5 - <?php echo $helper->__("Maio") ?></option>
                                <option value="06">6 - <?php echo $helper->__("Junho") ?></option>
                                <option value="07">7 - <?php echo $helper->__("Julho") ?></option>
                                <option value="08">8 - <?php echo $helper->__("Agosto") ?></option>
                                <option value="09">9 - <?php echo $helper->__("Setembro") ?></option>
                                <option value="10">10 - <?php echo $helper->__("Outubro") ?></option>
                                <option value="11">11 - <?php echo $helper->__("Novembro") ?></option>
                                <option value="12">12 - <?php echo $helper->__("Dezembro") ?></option>
                            </select>
                        </div>
                    </div>
                    <div class="field card-card_cvv">
                        <label for="card_cvv" class="required"><em>*</em><?php echo $helper->__("Ano do Vencimento") ?></label>
                        <div class="input-box">
                            <select name="payment[<?php echo $_code ?>_expiration_yr]"  class="input-text required-entry validate-expiryyear" >
                                <option selected disabled><?php echo $helper->__("Year") ?></option>
                                <?php foreach ($this->years() as $year): ?>
                                   <option value="<?php echo $year?>"><?php echo $helper->__( $year ) ?></option>
                                <?php endforeach;?>
                                <option selected disabled><?php echo $helper->__("Year") ?></option>
                            </select>
                        </div>
                    </div>
                </div>
            </li>

            <li>
                <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" 
                        name="payment[<?php echo $_code ?>_cc_cid]"
                        maxlength="4" class="input-text cvv required-entry validate-cvv" id="<?php echo $_code ?>_cc_cid" />
                    </div>
                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    <input type="hidden" 
                    id="<?php echo $_code ?>_cc_finger_print" 
                    name="payment[<?php echo $_code ?>_cc_finger_print]" 
                    />
                </div>
            </li>
            <li>
                <div class="input-box">
                    <input type="hidden" id="<?php echo $_code ?>_cc_split_number_value" name="payment[<?php echo $_code ?>_cc_split_number_value]"/>
                    <label for="<?php echo $_code ?>_cc_split_number" class="required"><em>*</em><?php echo $helper->__('Parcelas') ?> </label><br/>
                    <select id="<?php echo $_code ?>_cc_split_number" style="width:252px;" 
                    name="payment[<?php echo $_code ?>_cc_split_number]" 
                    class="required-entry validate-installment-yapay" 
                    onchange="document.getElementById('<?php echo $_code ?>_cc_split_number_value').value = this.options[this.selectedIndex].text.replace(/.*R\$/,'').replace(/\,/,'.');">
                    <option value="0">Parcela(s)</option>
                    <?php if($intallmentsActive): ?>
                    <?php foreach ($intallments as $key => $value) : ?>
                        <?php if ($key == 0) { continue; } ?>
                        <option value="<?= ($key) ?>"><?= $value ?></option>
                    <?php endforeach; ?>
                    <?php endif; ?>
                    </select>
                </div>
            </li>
            <?php if($helper->getCaptureTaxCc() == '1'): ?>
                <label for="<?php echo $_code ?>_cc_cpf" class="required"><em>*</em> <?php echo $helper->__('CPF') ?> </label>      
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_cc_cpf" 
                    name="payment[<?php echo $_code ?>_cc_cpf]" 
                    title="<?php echo $helper->__('CPF') ?>" 
                    class="required-entry validate-document-cpf"
                    autocomplete="off"/>
                </div>
            <?php endif; ?>
        </ul>

        <script type="text/javascript">
            $yapay(document).ready(function () {
                var fp = window.yapay.FingerPrint({ <?php echo $helper->getEnvironmentFingerPrint() ?> });
                document.getElementById('yapay_creditcardpayment_cc_finger_print').value = fp.getFingerPrint();
                var v = document.getElementById('yapay_creditcardpayment_cc_number');
                var resCc = identifyCreditCardTc(v.value.replace(/ /g,''));
                v.value = resCc;
                $yapay('#yapay_creditcardpayment_cc_number').change(function(){
                    var v = $yapay(this).val();
                    var resCc = identifyCreditCardTc(v.replace(/ /g,''));
                    $yapay(this).val(resCc);
                    <?php echo $splitJs; ?>
                });
                $yapay('#yapay_creditcardpayment_cc_cpf').on('input', function() {
                    var cpf = $yapay(this).val().replace(/\D/g, '');
                    var cpfFormatado = formatarCPF(cpf);
                    $yapay(this).val(cpfFormatado);
                });
            })
        </script>
</fieldset>
