<?php 
$_code = $this->getMethodCode(); 
$helper = Mage::helper("mageshop_yapay/data");
?>
<fieldset class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
      
        <ul data-yapay="payment-form">
            <input type="hidden" id="url_controller" value="<?php echo Mage::getUrl('yapay'); ?>">
            <input type="hidden" id="<?php echo $_code ?>_cc_payment_code" name="payment[<?php echo $_code ?>_cc_payment_code]" class="required-entry" value=""/>
            <li>                   
                <div class="input-box">
                    <label for="<?php echo $_code ?>_cc_number">
                    <?php echo $helper->__('Credit Card Number') ?> </label><br/>
                    <input type="text" id="<?php echo $_code ?>_cc_number" 
                    name="payment[<?php echo $_code ?>_cc_number]" 
                    title="<?php echo $helper->__('Credit Card Number') ?>" 
                    class="required-entry input-text validate-cc-number" 
                    placeholder="&bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull;" 
                    autocomplete="off"/>
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_cc_owner"><?php echo $helper->__('Name on Card') ?> </label><br/>
                    <input type="text" title="<?php echo $helper->__('Name on Card') ?>"
                    name="payment[<?php echo $_code ?>_cc_name]"
                    class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" 
                    name="payment[<?php echo $_code ?>_cc_name]" 
                    placeholder="JOHN DOE" onkeypress="return apenasLetras(event,this);"/>
                </div>
            </li>            

            <li class="fields">
                <div class="card-data">
                    <div class="field card-expires_at">
                        <label for="expires_at" class="required">
                            <?php echo $helper->__("Mês Vencimento") ?><em>*</em>
                        </label>
                        <div class="input-box">
                            <select name="<?php echo $_code ?>_expiration" class="input-text required-entry validate-expirymonth" >
                                <option selected disabled><?php echo $helper->__("Month") ?></option>
                                <option value="01"><?php echo $helper->__("January") ?> - 01</option>
                                <option value="02"><?php echo $helper->__("February") ?> - 02</option>
                                <option value="03"><?php echo $helper->__("March") ?> - 03</option>
                                <option value="04"><?php echo $helper->__("April") ?> - 04</option>
                                <option value="05"><?php echo $helper->__("May") ?> - 05</option>
                                <option value="06"><?php echo $helper->__("June") ?> - 06</option>
                                <option value="07"><?php echo $helper->__("July") ?> - 07</option>
                                <option value="08"><?php echo $helper->__("August") ?> - 08</option>
                                <option value="09"><?php echo $helper->__("Septembre") ?> - 09</option>
                                <option value="10"><?php echo $helper->__("Octobre") ?> - 10</option>
                                <option value="11"><?php echo $helper->__("Novembre") ?> - 11</option>
                                <option value="12"><?php echo $helper->__("Decembre") ?> - 12</option>
                            </select>
                        </div>
                    </div>
                    <div class="field card-card_cvv">
                        <label for="card_cvv" class="required"><?php echo $helper->__("Ano do Vencimento") ?><em>*</em></label>
                        <div class="input-box">
                            <select name="<?php echo $_code ?>_expiration_yr"  class="input-text required-entry validate-expiryyear" >
                                <option selected disabled><?php echo $helper->__("Year") ?></option>
                            </select>
                            <input type="hidden"id="<?php echo $_code ?>_cc_expdate" class="input-text required-entry validate-expires_at" name="payment[<?php echo $_code ?>_cc_expdate]" autocomplete="off"/>
                        </div>
                    </div>
                </div>
            </li>

            <li>
                <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" 
                        name="payment[<?php echo $_code ?>_cc_cid]"
                        maxlength="4" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" />
                    </div>
                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    <input type="hidden" 
                    id="<?php echo $_code ?>_cc_finger_print" 
                    name="payment[<?php echo $_code ?>_cc_finger_print]" 
                    />
                </div>
            </li>
            <li>
                <div class="input-box">
                    <input type="hidden" id="<?php echo $_code ?>_cc_split_number_value" name="payment[<?php echo $_code ?>_cc_split_number_value]"/>
                    <label for="<?php echo $_code ?>_cc_split_number"><?php echo $helper->__('Parcelas') ?> </label><br/>
                    <select id="<?php echo $_code ?>_cc_split_number" style="width:252px;" 
                    name="payment[<?php echo $_code ?>_cc_split_number]" 
                    class="required-entry" onchange="document.getElementById('<?php echo $_code ?>_cc_split_number_value').value = this.options[this.selectedIndex].text.replace(/.*R\$/,'').replace(/\,/,'.');">
                    <option value="1">Parcela(s)</option>
                    </select>
                </div>
            </li>
        </ul>

        <script type="text/javascript">
            $yapay(document).ready(function () {
                var fp = window.yapay.FingerPrint({ <?php echo $helper->getEnvironmentFingerPrint() ?> });
                document.getElementById('yapay_creditcardpayment_cc_finger_print').value = fp.getFingerPrint();
                var v = document.getElementById('yapay_creditcardpayment_cc_number');
                var resCc = identifyCreditCardTc(v.value.replace(/ /g,''));
                v.value = resCc;

                $yapay('#yapay_creditcardpayment_cc_number').change(function(){
                    var v = $yapay(this).val();
                    var resCc = identifyCreditCardTc(v.replace(/ /g,''));
                    $yapay(this).val(resCc);
                    getSplitValues();
                });

            })
        </script>
</fieldset>
<script></script>