<?php 
$_code = $this->getMethodCode(); 
$helper = $this->getHelper();
$totals = Mage::getSingleton('checkout/session')->getQuote()->getBaseGrandTotal();
?>
<fieldset class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <ul data-yapay="payment-form">
        <?php if($helper->getCaptureTaxCc() == '1'): ?>
        <li>
            <label for="<?php echo $_code ?>_cc_cpf"> <?php echo $helper->__('CPF') ?> </label>      
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_pix_cpf" 
                    name="payment[<?php echo $_code ?>_cc_cpf]" 
                    title="<?php echo $helper->__('CPF') ?>" 
                    class="required-entry validate-document-cpf"
                    autocomplete="off"/>
            </div>
        </li>
        <?php endif; ?>
    </ul>
</fieldset>
